[package]
name = "probor"
version = "0.1.1"
authors = ["Paul Colomiets <paul@colomiets.name>"]
license = "MIT"
repository = "https://github.com/tailhook/probor"
description = """
    A (prototype of) serialization protocol on top of CBOR that provides
    protobuf-like functionality
"""

[dependencies]
cbor-codec = "*"
byteorder = "*"

[lib]
name = "probor"
path = "src/lib.rs"
